-- Supabase schema for school management dashboard.
-- Run this in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  teacher_id text not null,
  name text not null,
  email text not null,
  photo text,
  phone text,
  subjects text[] not null default '{}',
  classes text[] not null default '{}',
  address text,
  blood_type text,
  birthday date,
  sex text check (sex in ('MALE', 'FEMALE', 'OTHER')),
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  student_id text not null,
  name text not null,
  email text not null,
  photo text,
  phone text,
  grade integer not null default 0,
  class text not null,
  address text,
  parent text,
  sex text check (sex in ('MALE', 'FEMALE', 'OTHER')),
  blood_type text,
  birthday date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.parents (
  id bigint generated by default as identity primary key,
  name text not null,
  students text[] not null default '{}',
  email text not null,
  phone text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  teachers text[] not null default '{}',
  code text,
  lessons_count integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  capacity integer not null default 0,
  grade integer not null default 0,
  supervisor text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  subject text not null,
  class text not null,
  teacher text not null,
  day text,
  start_time time,
  end_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  subject text not null,
  class text not null,
  teacher text not null,
  date date not null,
  start_time time,
  end_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  subject text not null,
  class text not null,
  teacher text not null,
  due_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  subject text not null,
  class text not null,
  teacher text not null,
  student text not null,
  date date not null,
  type text not null check (type in ('exam', 'assignment')),
  score integer not null check (score >= 0 and score <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  class text not null default 'All Classes',
  date date not null,
  start_time time not null,
  end_time time not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  class text not null default 'All Classes',
  date date not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  student_name text not null,
  class text not null,
  date date not null,
  status text not null check (status in ('PRESENT', 'ABSENT', 'LATE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_records_student_date_key unique (student_id, date)
);

create index if not exists teachers_name_idx on public.teachers (name);
create index if not exists students_name_idx on public.students (name);
create index if not exists students_class_idx on public.students (class);
create index if not exists attendance_records_date_idx on public.attendance_records (date);
create index if not exists announcements_date_idx on public.announcements (date desc);
create index if not exists events_date_idx on public.events (date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_teachers_updated_at on public.teachers;
create trigger set_teachers_updated_at
before update on public.teachers
for each row execute function public.set_updated_at();

drop trigger if exists set_students_updated_at on public.students;
create trigger set_students_updated_at
before update on public.students
for each row execute function public.set_updated_at();

drop trigger if exists set_parents_updated_at on public.parents;
create trigger set_parents_updated_at
before update on public.parents
for each row execute function public.set_updated_at();

drop trigger if exists set_subjects_updated_at on public.subjects;
create trigger set_subjects_updated_at
before update on public.subjects
for each row execute function public.set_updated_at();

drop trigger if exists set_classes_updated_at on public.classes;
create trigger set_classes_updated_at
before update on public.classes
for each row execute function public.set_updated_at();

drop trigger if exists set_lessons_updated_at on public.lessons;
create trigger set_lessons_updated_at
before update on public.lessons
for each row execute function public.set_updated_at();

drop trigger if exists set_exams_updated_at on public.exams;
create trigger set_exams_updated_at
before update on public.exams
for each row execute function public.set_updated_at();

drop trigger if exists set_assignments_updated_at on public.assignments;
create trigger set_assignments_updated_at
before update on public.assignments
for each row execute function public.set_updated_at();

drop trigger if exists set_results_updated_at on public.results;
create trigger set_results_updated_at
before update on public.results
for each row execute function public.set_updated_at();

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists set_announcements_updated_at on public.announcements;
create trigger set_announcements_updated_at
before update on public.announcements
for each row execute function public.set_updated_at();

drop trigger if exists set_attendance_records_updated_at on public.attendance_records;
create trigger set_attendance_records_updated_at
before update on public.attendance_records
for each row execute function public.set_updated_at();

alter table public.teachers enable row level security;
alter table public.students enable row level security;
alter table public.parents enable row level security;
alter table public.subjects enable row level security;
alter table public.classes enable row level security;
alter table public.lessons enable row level security;
alter table public.exams enable row level security;
alter table public.assignments enable row level security;
alter table public.results enable row level security;
alter table public.events enable row level security;
alter table public.announcements enable row level security;
alter table public.attendance_records enable row level security;