import {
  Teacher,
  Student,
  Parent,
  Subject,
  ClassItem,
  Lesson,
  Exam,
  Assignment,
  Result,
  EventItem,
  AnnouncementItem,
  TimetableEvent,
  AttendanceRecord,
} from "@/types";

export let role: string = "admin";

export const teachersData: Teacher[] = [
  {
    id: 1,
    teacherId: "TCH-1001",
    name: "Alexander Dean",
    email: "alexander.dean@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8901",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Springville, CA",
    bloodType: "A+",
    birthday: "1984-05-12",
    sex: "MALE",
    bio: "Passionate mathematics educator with 12+ years of experience transforming complex theorems into intuitive insights.",
  },
  {
    id: 2,
    teacherId: "TCH-1002",
    name: "Sarah Jenkins",
    email: "sarah.j@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8902",
    subjects: ["Physics", "Chemistry"],
    classes: ["4B", "5A"],
    address: "456 Elmwood Ave, Springville, CA",
    bloodType: "B+",
    birthday: "1988-11-23",
    sex: "FEMALE",
    bio: "Head of Science Department. Certified STEM researcher focusing on hands-on experimental laboratories.",
  },
  {
    id: 3,
    teacherId: "TCH-1003",
    name: "Michael Chang",
    email: "m.chang@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8903",
    subjects: ["Biology"],
    classes: ["1A", "3B", "4A"],
    address: "789 Oakridge Rd, Springville, CA",
    bloodType: "O+",
    birthday: "1990-03-15",
    sex: "MALE",
    bio: "Botanist and ecology enthusiast dedicated to environmental awareness in modern curriculum.",
  },
  {
    id: 4,
    teacherId: "TCH-1004",
    name: "Elena Rostova",
    email: "elena.r@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8904",
    subjects: ["History", "Social Studies"],
    classes: ["2B", "3A", "5B"],
    address: "321 Pinecrest Blvd, Springville, CA",
    bloodType: "AB-",
    birthday: "1986-07-30",
    sex: "FEMALE",
    bio: "World history specialist with published work on Mediterranean ancient civilizations.",
  },
  {
    id: 5,
    teacherId: "TCH-1005",
    name: "David Kim",
    email: "david.kim@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8905",
    subjects: ["English", "Literature"],
    classes: ["1C", "2C", "4C"],
    address: "654 Birchway Ln, Springville, CA",
    bloodType: "A-",
    birthday: "1991-09-08",
    sex: "MALE",
    bio: "Shakespearean scholar and creative writing mentor guiding student journalism.",
  },
  {
    id: 6,
    teacherId: "TCH-1006",
    name: "Chloe Dubois",
    email: "chloe.d@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8906",
    subjects: ["French", "Spanish"],
    classes: ["1A", "2A", "3A"],
    address: "987 Cedar Glen, Springville, CA",
    bloodType: "O-",
    birthday: "1993-01-19",
    sex: "FEMALE",
    bio: "Polyglot educator emphasizing immersive conversational techniques and cross-cultural exchanges.",
  },
  {
    id: 7,
    teacherId: "TCH-1007",
    name: "Marcus Vance",
    email: "m.vance@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8907",
    subjects: ["Computer Science", "Robotics"],
    classes: ["4A", "5A", "6A"],
    address: "159 Cypress Way, Springville, CA",
    bloodType: "B-",
    birthday: "1989-12-04",
    sex: "MALE",
    bio: "Former software engineer leading the school robotics and coding academy.",
  },
  {
    id: 8,
    teacherId: "TCH-1008",
    name: "Rachel Green",
    email: "rachel.g@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    phone: "+1 234 567 8908",
    subjects: ["Art", "Design"],
    classes: ["1B", "2B", "3B"],
    address: "753 Maple Terr, Springville, CA",
    bloodType: "O+",
    birthday: "1992-04-18",
    sex: "FEMALE",
    bio: "Fine arts graduate encouraging experimental digital and canvas creativity.",
  },
];

export const studentsData: Student[] = [
  {
    id: 1,
    studentId: "STD-2024-001",
    name: "Lucas Bennett",
    email: "lucas.b@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9012",
    grade: 10,
    class: "10A",
    address: "14 Willow St, Springville, CA",
    parent: "Thomas Bennett",
    sex: "MALE",
    bloodType: "O+",
    birthday: "2008-04-14",
  },
  {
    id: 2,
    studentId: "STD-2024-002",
    name: "Sophia Martinez",
    email: "sophia.m@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9013",
    grade: 10,
    class: "10A",
    address: "88 Walnut Ct, Springville, CA",
    parent: "Carlos Martinez",
    sex: "FEMALE",
    bloodType: "A+",
    birthday: "2008-08-21",
  },
  {
    id: 3,
    studentId: "STD-2024-003",
    name: "Ethan Wright",
    email: "ethan.w@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9014",
    grade: 9,
    class: "9B",
    address: "42 Magnolia Ave, Springville, CA",
    parent: "Jessica Wright",
    sex: "MALE",
    bloodType: "B+",
    birthday: "2009-02-10",
  },
  {
    id: 4,
    studentId: "STD-2024-004",
    name: "Ava Johnson",
    email: "ava.j@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9015",
    grade: 11,
    class: "11A",
    address: "51 Redwood Dr, Springville, CA",
    parent: "Robert Johnson",
    sex: "FEMALE",
    bloodType: "AB+",
    birthday: "2007-06-03",
  },
  {
    id: 5,
    studentId: "STD-2024-005",
    name: "Noah Patel",
    email: "noah.p@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9016",
    grade: 10,
    class: "10B",
    address: "99 Sunset Blvd, Springville, CA",
    parent: "Anil Patel",
    sex: "MALE",
    bloodType: "A-",
    birthday: "2008-11-19",
  },
  {
    id: 6,
    studentId: "STD-2024-006",
    name: "Mia Robinson",
    email: "mia.r@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9017",
    grade: 12,
    class: "12A",
    address: "73 Highland Pl, Springville, CA",
    parent: "Grace Robinson",
    sex: "FEMALE",
    bloodType: "O-",
    birthday: "2006-09-28",
  },
  {
    id: 7,
    studentId: "STD-2024-007",
    name: "Liam O'Connor",
    email: "liam.oc@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9018",
    grade: 9,
    class: "9A",
    address: "62 Aspen Way, Springville, CA",
    parent: "Sean O'Connor",
    sex: "MALE",
    bloodType: "B-",
    birthday: "2009-07-15",
  },
  {
    id: 8,
    studentId: "STD-2024-008",
    name: "Emma Davis",
    email: "emma.d@lamaedu.com",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "+1 345 678 9019",
    grade: 11,
    class: "11B",
    address: "310 Valley View, Springville, CA",
    parent: "Hannah Davis",
    sex: "FEMALE",
    bloodType: "A+",
    birthday: "2007-12-05",
  },
];

export const parentsData: Parent[] = [
  {
    id: 1,
    name: "Thomas Bennett",
    students: ["Lucas Bennett"],
    email: "t.bennett@example.com",
    phone: "+1 456 789 0123",
    address: "14 Willow St, Springville, CA",
  },
  {
    id: 2,
    name: "Carlos Martinez",
    students: ["Sophia Martinez"],
    email: "carlos.m@example.com",
    phone: "+1 456 789 0124",
    address: "88 Walnut Ct, Springville, CA",
  },
  {
    id: 3,
    name: "Jessica Wright",
    students: ["Ethan Wright"],
    email: "j.wright@example.com",
    phone: "+1 456 789 0125",
    address: "42 Magnolia Ave, Springville, CA",
  },
  {
    id: 4,
    name: "Robert Johnson",
    students: ["Ava Johnson"],
    email: "r.johnson@example.com",
    phone: "+1 456 789 0126",
    address: "51 Redwood Dr, Springville, CA",
  },
  {
    id: 5,
    name: "Anil Patel",
    students: ["Noah Patel"],
    email: "a.patel@example.com",
    phone: "+1 456 789 0127",
    address: "99 Sunset Blvd, Springville, CA",
  },
  {
    id: 6,
    name: "Grace Robinson",
    students: ["Mia Robinson"],
    email: "g.robinson@example.com",
    phone: "+1 456 789 0128",
    address: "73 Highland Pl, Springville, CA",
  },
];

export const subjectsData: Subject[] = [
  {
    id: 1,
    name: "Mathematics",
    teachers: ["Alexander Dean", "Marcus Vance"],
    code: "MATH-101",
    lessonsCount: 14,
  },
  {
    id: 2,
    name: "Physics",
    teachers: ["Sarah Jenkins"],
    code: "PHYS-201",
    lessonsCount: 8,
  },
  {
    id: 3,
    name: "Chemistry",
    teachers: ["Sarah Jenkins"],
    code: "CHEM-202",
    lessonsCount: 6,
  },
  {
    id: 4,
    name: "Biology",
    teachers: ["Michael Chang"],
    code: "BIO-105",
    lessonsCount: 10,
  },
  {
    id: 5,
    name: "History",
    teachers: ["Elena Rostova"],
    code: "HIST-301",
    lessonsCount: 12,
  },
  {
    id: 6,
    name: "English Literature",
    teachers: ["David Kim"],
    code: "ENG-102",
    lessonsCount: 16,
  },
  {
    id: 7,
    name: "Computer Science",
    teachers: ["Marcus Vance"],
    code: "CS-401",
    lessonsCount: 12,
  },
  {
    id: 8,
    name: "French",
    teachers: ["Chloe Dubois"],
    code: "FR-101",
    lessonsCount: 6,
  },
  {
    id: 9,
    name: "Fine Arts",
    teachers: ["Rachel Green"],
    code: "ART-103",
    lessonsCount: 4,
  },
];

export const classesData: ClassItem[] = [
  {
    id: 1,
    name: "9A",
    capacity: 25,
    grade: 9,
    supervisor: "Michael Chang",
  },
  {
    id: 2,
    name: "9B",
    capacity: 28,
    grade: 9,
    supervisor: "David Kim",
  },
  {
    id: 3,
    name: "10A",
    capacity: 26,
    grade: 10,
    supervisor: "Alexander Dean",
  },
  {
    id: 4,
    name: "10B",
    capacity: 30,
    grade: 10,
    supervisor: "Elena Rostova",
  },
  {
    id: 5,
    name: "11A",
    capacity: 24,
    grade: 11,
    supervisor: "Sarah Jenkins",
  },
  {
    id: 6,
    name: "11B",
    capacity: 25,
    grade: 11,
    supervisor: "Chloe Dubois",
  },
  {
    id: 7,
    name: "12A",
    capacity: 22,
    grade: 12,
    supervisor: "Marcus Vance",
  },
];

export const lessonsData: Lesson[] = [
  {
    id: 1,
    subject: "Mathematics",
    class: "10A",
    teacher: "Alexander Dean",
    day: "Monday",
    startTime: "08:30",
    endTime: "09:45",
  },
  {
    id: 2,
    subject: "Physics",
    class: "10A",
    teacher: "Sarah Jenkins",
    day: "Monday",
    startTime: "10:00",
    endTime: "11:15",
  },
  {
    id: 3,
    subject: "English Literature",
    class: "10A",
    teacher: "David Kim",
    day: "Monday",
    startTime: "11:30",
    endTime: "12:45",
  },
  {
    id: 4,
    subject: "Biology",
    class: "9B",
    teacher: "Michael Chang",
    day: "Tuesday",
    startTime: "08:30",
    endTime: "09:45",
  },
  {
    id: 5,
    subject: "Computer Science",
    class: "11A",
    teacher: "Marcus Vance",
    day: "Tuesday",
    startTime: "10:00",
    endTime: "11:15",
  },
  {
    id: 6,
    subject: "History",
    class: "10B",
    teacher: "Elena Rostova",
    day: "Wednesday",
    startTime: "09:00",
    endTime: "10:15",
  },
  {
    id: 7,
    subject: "French",
    class: "9A",
    teacher: "Chloe Dubois",
    day: "Wednesday",
    startTime: "10:30",
    endTime: "11:45",
  },
  {
    id: 8,
    subject: "Fine Arts",
    class: "10A",
    teacher: "Rachel Green",
    day: "Thursday",
    startTime: "13:00",
    endTime: "14:15",
  },
];

export const examsData: Exam[] = [
  {
    id: 1,
    subject: "Mathematics Mid-Term",
    class: "10A",
    teacher: "Alexander Dean",
    date: "2026-08-25",
    startTime: "09:00",
    endTime: "11:00",
  },
  {
    id: 2,
    subject: "Physics Practical Exam",
    class: "11A",
    teacher: "Sarah Jenkins",
    date: "2026-08-28",
    startTime: "10:00",
    endTime: "12:00",
  },
  {
    id: 3,
    subject: "English Literature Essay",
    class: "10B",
    teacher: "David Kim",
    date: "2026-09-02",
    startTime: "08:30",
    endTime: "10:30",
  },
  {
    id: 4,
    subject: "Biology Cell Structure Test",
    class: "9B",
    teacher: "Michael Chang",
    date: "2026-09-05",
    startTime: "11:00",
    endTime: "12:30",
  },
  {
    id: 5,
    subject: "Computer Science Algorithms",
    class: "12A",
    teacher: "Marcus Vance",
    date: "2026-09-10",
    startTime: "09:30",
    endTime: "11:30",
  },
];

export const assignmentsData: Assignment[] = [
  {
    id: 1,
    subject: "Calculus Problem Set #4",
    class: "10A",
    teacher: "Alexander Dean",
    dueDate: "2026-08-22",
  },
  {
    id: 2,
    subject: "Thermodynamics Lab Report",
    class: "11A",
    teacher: "Sarah Jenkins",
    dueDate: "2026-08-24",
  },
  {
    id: 3,
    subject: "Hamlet Critical Character Analysis",
    class: "10A",
    teacher: "David Kim",
    dueDate: "2026-08-27",
  },
  {
    id: 4,
    subject: "Photosynthesis Presentation",
    class: "9A",
    teacher: "Michael Chang",
    dueDate: "2026-08-29",
  },
  {
    id: 5,
    subject: "Python Binary Search Trees Project",
    class: "12A",
    teacher: "Marcus Vance",
    dueDate: "2026-09-01",
  },
  {
    id: 6,
    subject: "French Verb Conjugations Exercise",
    class: "9B",
    teacher: "Chloe Dubois",
    dueDate: "2026-09-03",
  },
];

export const resultsData: Result[] = [
  {
    id: 1,
    subject: "Mathematics",
    class: "10A",
    teacher: "Alexander Dean",
    student: "Lucas Bennett",
    date: "2026-08-10",
    type: "exam",
    score: 94,
  },
  {
    id: 2,
    subject: "Physics",
    class: "10A",
    teacher: "Sarah Jenkins",
    student: "Sophia Martinez",
    date: "2026-08-11",
    type: "exam",
    score: 88,
  },
  {
    id: 3,
    subject: "English Literature",
    class: "10A",
    teacher: "David Kim",
    student: "Lucas Bennett",
    date: "2026-08-12",
    type: "assignment",
    score: 92,
  },
  {
    id: 4,
    subject: "Biology",
    class: "9B",
    teacher: "Michael Chang",
    student: "Ethan Wright",
    date: "2026-08-14",
    type: "exam",
    score: 79,
  },
  {
    id: 5,
    subject: "Computer Science",
    class: "11A",
    teacher: "Marcus Vance",
    student: "Ava Johnson",
    date: "2026-08-15",
    type: "assignment",
    score: 98,
  },
  {
    id: 6,
    subject: "History",
    class: "10B",
    teacher: "Elena Rostova",
    student: "Noah Patel",
    date: "2026-08-15",
    type: "exam",
    score: 85,
  },
];

export const eventsData: EventItem[] = [
  {
    id: 1,
    title: "Annual STEM & Science Fair",
    class: "All Classes",
    date: "2026-08-20",
    startTime: "09:00",
    endTime: "14:00",
    description: "Students showcase innovative science projects, robotics, and interactive chemistry demonstrations.",
  },
  {
    id: 2,
    title: "Parent-Teacher Conference (Q3)",
    class: "All Classes",
    date: "2026-08-22",
    startTime: "13:00",
    endTime: "17:30",
    description: "One-on-one progress review between parents and class supervisors in the Main Auditorium.",
  },
  {
    id: 3,
    title: "Inter-School Basketball Championship",
    class: "Grade 10-12",
    date: "2026-08-26",
    startTime: "15:00",
    endTime: "18:00",
    description: "Semi-finals match against Oakridge Academy at the School Sports Complex.",
  },
  {
    id: 4,
    title: "National Coding Olympiad Prep",
    class: "Grade 11 & 12",
    date: "2026-08-29",
    startTime: "14:30",
    endTime: "16:30",
    description: "Specialized algorithmic training session led by Marcus Vance in Computer Lab 2.",
  },
];

export const announcementsData: AnnouncementItem[] = [
  {
    id: 1,
    title: "New Semester Timetable Published",
    class: "All Classes",
    date: "2026-08-15",
    description: "Please check your updated weekly schedules and room allocations under the Timetable tab. Lab sessions begin promptly on Monday.",
  },
  {
    id: 2,
    title: "Library Books Return Deadline",
    class: "Grade 10 & 11",
    date: "2026-08-14",
    description: "All borrowed literature books and reference manuals must be returned or renewed by Friday afternoon to avoid late fees.",
  },
  {
    id: 3,
    title: "Sports Day Uniform & Registration",
    class: "All Classes",
    date: "2026-08-12",
    description: "Registration for track and field events is now open. Official house jerseys will be distributed during homeroom periods.",
  },
  {
    id: 4,
    title: "Math Olympiad Registration Closes Soon",
    class: "Grade 9 & 10",
    date: "2026-08-10",
    description: "Students interested in participating in the Regional Mathematics Olympiad should submit their forms to Alexander Dean.",
  },
];

export const timetableEvents: TimetableEvent[] = [
  {
    id: 1,
    title: "Mathematics (Algebra II)",
    day: "Monday",
    startTime: "08:30",
    endTime: "09:45",
    teacher: "Alexander Dean",
    class: "10A",
    room: "Room 102",
    colorBg: "bg-lamaSkyLight",
    colorBorder: "border-l-lamaSky",
  },
  {
    id: 2,
    title: "Physics (Mechanics)",
    day: "Monday",
    startTime: "10:00",
    endTime: "11:15",
    teacher: "Sarah Jenkins",
    class: "10A",
    room: "Science Lab B",
    colorBg: "bg-lamaPurpleLight",
    colorBorder: "border-l-lamaPurple",
  },
  {
    id: 3,
    title: "English Literature",
    day: "Monday",
    startTime: "11:30",
    endTime: "12:45",
    teacher: "David Kim",
    class: "10A",
    room: "Room 204",
    colorBg: "bg-lamaYellowLight",
    colorBorder: "border-l-lamaYellow",
  },
  {
    id: 4,
    title: "World History",
    day: "Tuesday",
    startTime: "08:30",
    endTime: "09:45",
    teacher: "Elena Rostova",
    class: "10A",
    room: "Room 108",
    colorBg: "bg-lamaYellowLight",
    colorBorder: "border-l-lamaYellow",
  },
  {
    id: 5,
    title: "Computer Science Lab",
    day: "Tuesday",
    startTime: "10:00",
    endTime: "11:30",
    teacher: "Marcus Vance",
    class: "10A",
    room: "Lab 3",
    colorBg: "bg-lamaSkyLight",
    colorBorder: "border-l-lamaSky",
  },
  {
    id: 6,
    title: "Physical Education",
    day: "Tuesday",
    startTime: "13:00",
    endTime: "14:15",
    teacher: "Coach Taylor",
    class: "10A",
    room: "Gymnasium",
    colorBg: "bg-lamaPurpleLight",
    colorBorder: "border-l-lamaPurple",
  },
  {
    id: 7,
    title: "Chemistry (Organic)",
    day: "Wednesday",
    startTime: "09:00",
    endTime: "10:30",
    teacher: "Sarah Jenkins",
    class: "10A",
    room: "Lab 1",
    colorBg: "bg-lamaSkyLight",
    colorBorder: "border-l-lamaSky",
  },
  {
    id: 8,
    title: "French Language",
    day: "Wednesday",
    startTime: "11:00",
    endTime: "12:15",
    teacher: "Chloe Dubois",
    class: "10A",
    room: "Room 201",
    colorBg: "bg-lamaYellowLight",
    colorBorder: "border-l-lamaYellow",
  },
  {
    id: 9,
    title: "Mathematics (Trigonometry)",
    day: "Thursday",
    startTime: "08:30",
    endTime: "09:45",
    teacher: "Alexander Dean",
    class: "10A",
    room: "Room 102",
    colorBg: "bg-lamaSkyLight",
    colorBorder: "border-l-lamaSky",
  },
  {
    id: 10,
    title: "Fine Arts & Digital Design",
    day: "Thursday",
    startTime: "10:15",
    endTime: "12:00",
    teacher: "Rachel Green",
    class: "10A",
    room: "Studio 4",
    colorBg: "bg-lamaPurpleLight",
    colorBorder: "border-l-lamaPurple",
  },
  {
    id: 11,
    title: "Biology (Genetics)",
    day: "Friday",
    startTime: "09:00",
    endTime: "10:30",
    teacher: "Michael Chang",
    class: "10A",
    room: "Bio Lab",
    colorBg: "bg-lamaYellowLight",
    colorBorder: "border-l-lamaYellow",
  },
  {
    id: 12,
    title: "Class Advisory & Assembly",
    day: "Friday",
    startTime: "11:00",
    endTime: "12:15",
    teacher: "Alexander Dean",
    class: "10A",
    room: "Main Hall",
    colorBg: "bg-lamaSkyLight",
    colorBorder: "border-l-lamaSky",
  },
];

export const weeklyAttendanceData = [
  { name: "Mon", present: 88, absent: 12 },
  { name: "Tue", present: 94, absent: 6 },
  { name: "Wed", present: 91, absent: 9 },
  { name: "Thu", present: 96, absent: 4 },
  { name: "Fri", present: 85, absent: 15 },
];

export const monthlyFinanceData = [
  { name: "Jan", income: 42000, expense: 31000 },
  { name: "Feb", income: 38000, expense: 29000 },
  { name: "Mar", income: 51000, expense: 34000 },
  { name: "Apr", income: 48000, expense: 36000 },
  { name: "May", income: 54000, expense: 38000 },
  { name: "Jun", income: 62000, expense: 41000 },
  { name: "Jul", income: 59000, expense: 39000 },
  { name: "Aug", income: 68000, expense: 43000 },
  { name: "Sep", income: 72000, expense: 46000 },
  { name: "Oct", income: 69000, expense: 44000 },
  { name: "Nov", income: 76000, expense: 48000 },
  { name: "Dec", income: 84000, expense: 52000 },
];

export const studentCountBreakdown = [
  { name: "Total", count: 1234, fill: "white" },
  { name: "Boys", count: 678, fill: "#C3EBFA" },
  { name: "Girls", count: 556, fill: "#FAE27C" },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  { id: 1, studentId: 1, studentName: "Lucas Bennett", class: "10A", date: "2026-08-16", status: "PRESENT" },
  { id: 2, studentId: 2, studentName: "Sophia Martinez", class: "10A", date: "2026-08-16", status: "PRESENT" },
  { id: 3, studentId: 3, studentName: "Ethan Wright", class: "9B", date: "2026-08-16", status: "LATE" },
  { id: 4, studentId: 4, studentName: "Ava Johnson", class: "11A", date: "2026-08-16", status: "PRESENT" },
  { id: 5, studentId: 5, studentName: "Noah Patel", class: "10B", date: "2026-08-16", status: "ABSENT" },
  { id: 6, studentId: 6, studentName: "Mia Robinson", class: "12A", date: "2026-08-16", status: "PRESENT" },
  { id: 7, studentId: 7, studentName: "Liam O'Connor", class: "9A", date: "2026-08-16", status: "PRESENT" },
  { id: 8, studentId: 8, studentName: "Emma Davis", class: "11B", date: "2026-08-16", status: "PRESENT" },
];
